### ISSUE TITLE
很好的数据，就是不知道是否爬取的完整。

### ISSUE THREAD

**Issue by bashanyeyu** [AmorChao/TrainCrawler#1]
我打开了12306那个包含车次名称、始发站和终点站的api，不知道您当时爬取的时候是否爬取的完整，对应via文件中的车次经停站点是否完全？谢谢！数据很有用。

**Comment by MogicianXD** [comment]
谢谢！应该不完整，因为火车票网的经停站表并不是最新的，有一些车站不存在于12306官方json里，我在生成via.csv时忽略了这些车站，info.csv是原始的爬取结果。此外，对于一些新的列车号，火车票网没有相应的经停站表，我生成tid.csv时忽略了这些列车，raw_train.csv有全部的列车号

**Comment by bashanyeyu** [comment]
是不是流程这样子：根据https://kyfw.12306.cn/otn/resources/js/query/train_list.js?scriptVersion=1.0获取所有列车车次得到raw_train.csv，根据火车票网有记录的车次（tid.csv）爬取经停站等信息，生成info.csv，然后提出不在12306js记录中的车站，得到via.csv；

**Comment by MogicianXD** [comment]
是的

**Comment by bashanyeyu** [comment]
好的 再次表示感谢!
